[package]
name = "dvamm"
version = "3.0.0"
authors = ["Luis Quispe Gonzales", "Elena Maranon"]
edition = "2021"
description = "Common DVAMM types"
license = "Apache-2.0"

[dependencies]
cw20 = { version = "2.0.0" }
cosmwasm-std = { version = "2.0.4", features = ["iterator"] }
schemars = "0.8.21"
serde = { version = "1.0.203", default-features = false, features = ["derive"] }
uint = "0.9.5"

[dev-dependencies]
cosmwasm-schema = "2.0.4"
